#############
# 基础设置 #
#############

url: "https://rhmoon-github.github.io"
baseurl: ""
lang: "zh"
author: "rhmoon"
title: "rhmoon's blogs"
description: "小红帽的博客"
keywords: "rh"
favicon: "/img/favicon.ico"

# 谷歌分析
google-tracking-id: ""
# https
force-https: True
# disqus评论
# disqus-shortname: "personal-jekyll-theme"


################
# 首页 #
################

# 首页菜单左侧小图标 #
black-favicon: "/img/black-lab-glass.ico"
# 首页背景图 #
background-img: "../img/intro-bg.jpg"
# 首页头像 #
me-img: "/img/jetpacktocat.png"
# 首菜单栏索引
pages_list:
  关于: 'about'
  文章: 'latest-post'
  时间轴: 'timeline'
  社交: 'contact'


##############################
# 首页滚动字幕 #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "千里之行，始于足下"
  - text: "一个男人的背影能有多帅"



############
# 时间轴 #
############

events:
  - image: "/img/timeline/baracktocat.jpg"
    date: "2019-07-12"
    description: "解锁成就：创建小红帽博客"

# 时间轴开始图片

timeline-img: "/img/timeline/default.png"


########
# 博客 #
########

enable-gesture-navigation: True
# 可预览的博客数
post-preview-words: 10
# 每页显示的博客数
paginate: 10
# 文章首页
paginate_base_path: "/blog"
# 分页路径
paginate_path: "blog/page:num/"
# 语法高亮
syntax-highlight: True

################
# 作者简介 #
################

author_blurb: "如有不对，欢迎留言指正。虽然不懂前端技术，但不妨碍经营好小红帽的博客。"
author_blurb_image: "/img/author.png"