###############
# 基础设置
###############
title: rhmoon                                                                   #home页标题
SEOTitle: 小红帽的博客 | rhmoon's blog                                          #home页title
header-img: img/home-images/home-bg.jpeg                                        #home页背景图
# email: rhmoon@yeah.com                                                        #你的邮箱
description: "for time in mylife ; do learn compress and share ; done"          #你的座右铭
keyword: "rhmoon"                                                               
url: "https://rhmoon-github.github.io/"                                         #你的GitHub Pages地址
baseurl: ""      
github_repo: "https://github.com/rhmoon-github/rhmoon-github.github.io"         #你的GitHub仓库地址

############
# 侧边栏设置
############
sidebar: true                                                                   #是否开启侧边栏
sidebar-about-description: "小了红了帽"                                         #侧边栏描述
sidebar-avatar: /img/home-images/rhmoon.png                                     #侧边栏显示头像

############
# 社交账号
############
# SNS settings
RSS: false
weibo_username:                                                                  #微博
zhihu_username:                                                                  #知乎
github_username:    rhmoon-github                                                #GitHub
jianshu_username:                                                                #简书

###############
# Markdown设置
###############
markdown: kramdown                                                               # Github推荐使用kramdown作为markdown解析
highlighter: rouge                                                               # 语法高亮
kramdown:
  input: GFM


###############
# Disqus评论
###############
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

###############
# Gitalk评论
###############
gitalk:
  enable: true                                              #是否开启Gitalk评论
  clientID: 10e6a1a702be2240cc76                            #生成的clientID
  clientSecret: d24c16617090b8e4e6396a7b55008dd3be934a0f    #生成的clientSecret
  repo: rhmoon-github.github.io                             #仓库名称
  owner: rhmoon-github                                      #github用户名
  admin: rhmoon-github
  distractionFreeMode: true                                 #是否启用类似FB的阴影遮罩

###############
# 标签设置
###############
featured-tags: true                                         # 是否使用首页标签
featured-condition-size: 0                                  # 相同标签数量大于这个数，才会出现在首页


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true
